volumes:
  vol-nextjs:
  
services:

    nextjs:
        image: "next/nextui:234"
        # stdin_open: true # docker run -i
        # tty: true        # docker run -t        
        build:
            context: .
            dockerfile: Dockerfile
        command:
        - /bin/sh
        - -c
        - |
            npm run dev
        ports:
            - "3000:3000"
        restart: no
        volumes:
            - vol-nextjs:/opt
